import type { PermissionCode } from "./permissions";
import type { RoleCode } from "./roles";
import type { Scope } from "./scopes";

type Grant = { permission: PermissionCode; scope: Scope };

const ALL_OPS: PermissionCode[] = [
  "users.read",
  "users.create",
  "users.update",
  "users.disable",
  "users.assign_role",
  "applications.read",
  "applications.create",
  "applications.update",
  "applications.review",
  "applications.approve",
  "applications.reject",
  "projects.read",
  "projects.create",
  "projects.update",
  "projects.archive",
  "projects.assign_coach",
  "coaching.read",
  "coaching.create",
  "coaching.update",
  "coaching.evaluate",
  "coaching.private_notes",
  "evaluations.read",
  "evaluations.create",
  "evaluations.update",
  "evaluations.submit",
  "documents.read",
  "documents.upload",
  "documents.update",
  "documents.delete",
  "events.read",
  "events.create",
  "events.update",
  "events.publish",
  "events.delete",
  "resources.read",
  "resources.manage",
  "reports.read",
  "reports.generate",
  "reports.export",
  "settings.read",
  "settings.update",
  "audit.read",
];

function grantAll(scope: Scope): Grant[] {
  return ALL_OPS.map((permission) => ({ permission, scope }));
}

/**
 * Matriz role → permissões + escopo (spec §§5–15).
 * PLATFORM_ADMIN: administração técnica GLOBAL, sem coaching.private_notes automático
 * (conteúdo confidencial separado — remove-se private_notes do admin técnico).
 */
export const ROLE_PERMISSION_MATRIX: Record<RoleCode, Grant[]> = {
  PLATFORM_ADMIN: grantAll("GLOBAL").filter(
    (g) => g.permission !== "coaching.private_notes",
  ),

  INCUBATOR_COORDINATOR: [
    { permission: "users.read", scope: "INCUBATOR" },
    { permission: "users.create", scope: "INCUBATOR" },
    { permission: "users.update", scope: "INCUBATOR" },
    { permission: "users.assign_role", scope: "INCUBATOR" },
    { permission: "applications.read", scope: "INCUBATOR" },
    { permission: "applications.create", scope: "INCUBATOR" },
    { permission: "applications.update", scope: "INCUBATOR" },
    { permission: "applications.review", scope: "INCUBATOR" },
    { permission: "applications.approve", scope: "INCUBATOR" },
    { permission: "applications.reject", scope: "INCUBATOR" },
    { permission: "projects.read", scope: "INCUBATOR" },
    { permission: "projects.create", scope: "INCUBATOR" },
    { permission: "projects.update", scope: "INCUBATOR" },
    { permission: "projects.archive", scope: "INCUBATOR" },
    { permission: "projects.assign_coach", scope: "INCUBATOR" },
    { permission: "coaching.read", scope: "INCUBATOR" },
    { permission: "coaching.create", scope: "INCUBATOR" },
    { permission: "coaching.update", scope: "INCUBATOR" },
    { permission: "coaching.evaluate", scope: "INCUBATOR" },
    { permission: "coaching.private_notes", scope: "INCUBATOR" },
    { permission: "evaluations.read", scope: "INCUBATOR" },
    { permission: "evaluations.create", scope: "INCUBATOR" },
    { permission: "evaluations.update", scope: "INCUBATOR" },
    { permission: "documents.read", scope: "INCUBATOR" },
    { permission: "documents.upload", scope: "INCUBATOR" },
    { permission: "documents.update", scope: "INCUBATOR" },
    { permission: "documents.delete", scope: "INCUBATOR" },
    { permission: "events.read", scope: "INCUBATOR" },
    { permission: "events.create", scope: "INCUBATOR" },
    { permission: "events.update", scope: "INCUBATOR" },
    { permission: "events.publish", scope: "INCUBATOR" },
    { permission: "events.delete", scope: "INCUBATOR" },
    { permission: "resources.read", scope: "INCUBATOR" },
    { permission: "resources.manage", scope: "INCUBATOR" },
    { permission: "reports.read", scope: "INCUBATOR" },
    { permission: "reports.generate", scope: "INCUBATOR" },
    { permission: "reports.export", scope: "INCUBATOR" },
    { permission: "settings.read", scope: "INCUBATOR" },
    { permission: "settings.update", scope: "INCUBATOR" },
    { permission: "audit.read", scope: "INCUBATOR" },
  ],

  SECRETARIAT: [
    { permission: "users.read", scope: "INCUBATOR" },
    { permission: "applications.read", scope: "INCUBATOR" },
    { permission: "applications.create", scope: "INCUBATOR" },
    { permission: "applications.update", scope: "INCUBATOR" },
    { permission: "applications.review", scope: "INCUBATOR" },
    { permission: "projects.read", scope: "INCUBATOR" },
    { permission: "documents.read", scope: "INCUBATOR" },
    { permission: "documents.upload", scope: "INCUBATOR" },
    { permission: "events.read", scope: "INCUBATOR" },
    { permission: "events.create", scope: "INCUBATOR" },
    { permission: "events.update", scope: "INCUBATOR" },
    { permission: "resources.read", scope: "INCUBATOR" },
    { permission: "resources.manage", scope: "INCUBATOR" },
    { permission: "reports.read", scope: "INCUBATOR" },
  ],

  COACH: [
    { permission: "projects.read", scope: "ASSIGNED" },
    { permission: "projects.update", scope: "ASSIGNED" },
    { permission: "coaching.read", scope: "ASSIGNED" },
    { permission: "coaching.create", scope: "ASSIGNED" },
    { permission: "coaching.update", scope: "ASSIGNED" },
    { permission: "coaching.evaluate", scope: "ASSIGNED" },
    { permission: "coaching.private_notes", scope: "ASSIGNED" },
    { permission: "evaluations.read", scope: "ASSIGNED" },
    { permission: "evaluations.create", scope: "ASSIGNED" },
    { permission: "evaluations.update", scope: "ASSIGNED" },
    { permission: "evaluations.submit", scope: "ASSIGNED" },
    { permission: "documents.read", scope: "ASSIGNED" },
    { permission: "documents.upload", scope: "ASSIGNED" },
    { permission: "events.read", scope: "PUBLIC" },
    { permission: "reports.read", scope: "ASSIGNED" },
  ],

  PROJECT_MANAGER: [
    { permission: "projects.read", scope: "OWN" },
    { permission: "projects.update", scope: "OWN" },
    { permission: "applications.read", scope: "OWN" },
    { permission: "applications.create", scope: "OWN" },
    { permission: "coaching.read", scope: "OWN" },
    { permission: "evaluations.read", scope: "OWN" },
    { permission: "documents.read", scope: "OWN" },
    { permission: "documents.upload", scope: "OWN" },
    { permission: "users.read", scope: "TEAM" },
    { permission: "users.update", scope: "TEAM" },
    { permission: "events.read", scope: "PUBLIC" },
    { permission: "reports.read", scope: "OWN" },
  ],

  TEAM_MEMBER: [
    { permission: "projects.read", scope: "TEAM" },
    { permission: "coaching.read", scope: "TEAM" },
    { permission: "evaluations.read", scope: "TEAM" },
    { permission: "documents.read", scope: "TEAM" },
    { permission: "documents.upload", scope: "TEAM" },
    { permission: "users.read", scope: "TEAM" },
    { permission: "events.read", scope: "PUBLIC" },
    { permission: "reports.read", scope: "TEAM" },
  ],

  EVALUATOR: [
    { permission: "applications.read", scope: "ASSIGNED" },
    { permission: "projects.read", scope: "ASSIGNED" },
    { permission: "evaluations.read", scope: "ASSIGNED" },
    { permission: "evaluations.create", scope: "ASSIGNED" },
    { permission: "evaluations.update", scope: "ASSIGNED" },
    { permission: "evaluations.submit", scope: "ASSIGNED" },
    { permission: "documents.read", scope: "ASSIGNED" },
    { permission: "reports.read", scope: "ASSIGNED" },
  ],

  VISITOR: [
    { permission: "projects.read", scope: "PUBLIC" },
    { permission: "events.read", scope: "PUBLIC" },
    { permission: "applications.create", scope: "PUBLIC" },
    { permission: "documents.read", scope: "PUBLIC" },
    { permission: "resources.read", scope: "PUBLIC" },
    { permission: "reports.read", scope: "PUBLIC" },
  ],
};
